CREATE NONCLUSTERED INDEX [TblOrdersBOM_Items_idx] ON [dbo].[TblOrdersBOM_Items]
  ([ExceptionId])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX [TblOrdersBOM_Items_idx2] ON [dbo].[TblOrdersBOM_Items]
  ([PRC_EmployeeID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX [TblOrdersBOM_Items_idx3] ON [dbo].[TblOrdersBOM_Items]
  ([Final_EmployeeID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX [TblOrdersBOM_Items_idx4] ON [dbo].[TblOrdersBOM_Items]
  ([Prefinishing_Complete_EmployeeID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX [TblOrdersBOM_Items_idx5] ON [dbo].[TblOrdersBOM_Items]
  ([exceptionOpened_EmployeeID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX [TblOrdersBOM_Items_idx6] ON [dbo].[TblOrdersBOM_Items]
  ([ExceptionClosed_EmployeeID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX [TblOrdersBOM_Items_idx7] ON [dbo].[TblOrdersBOM_Items]
  ([outsource_EmployeeID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX [TblOrdersBOM_idx3] ON [dbo].[TblOrdersBOM]
  ([ProductionDate])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX [TblOrdersBOM_idx4] ON [dbo].[TblOrdersBOM]
  ([Duedate])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO


















CREATE NONCLUSTERED INDEX [TblOrdersBOM_idx5] ON [dbo].[TblOrdersBOM]
  ([CompanyID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX [TblOrdersBOM_idx6] ON [dbo].[TblOrdersBOM]
  ([ShippingMethodID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX [Products_idx] ON [dbo].[Products]
  ([CompanyID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX [Products_idx2] ON [dbo].[Products]
  ([SpeciesID])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX [TblOrdersBOM_idx7] ON [dbo].[TblOrdersBOM]
  ([EmployeeIDReportedReadyToShip])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX [tbl_settings_idx] ON [dbo].[tbl_settings]
  ([d_company_id])
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO