ALTER TABLE `tbl_settings_per_company`
	ADD COLUMN `d_email_css` VARCHAR(2000) NULL DEFAULT NULL AFTER `d_email_header`;


UPDATE `tbl_settings_per_company` SET `d_email_css`='	<style type="text/css">\r\n		body,\r\n		#message__100                  { margin:0; padding:0; text-align:center; background-color:#e2e3c3; color:black;\r\n											font-family:Tahoma, Arial, sanf-serif; font-size:11px; }\r\n		#message__100 td               { vertical-align:top; font-size:11px; }\r\n		#message__100 th               { vertical-align:top; font-size:11px; }\r\n		#message__100 #layout_content { width:600px; min-width:600px; margin-left:auto; margin-right:auto; text-align:left; }\r\n		#message__100 #logo           { padding:15px; color:#f1b91a; background-color:#4f4422; font-size:17px; text-align:right; }\r\n		#message__100 #logo img       { float:left; }\r\n		#message__100 #openHours      { color:white; font-size:12px; }\r\n		#message__100 #content        { padding:15px; background-color:white; }\r\n		#message__100 #footer         { padding:5px; color:#f1b91a; background-color:#4f4422; text-align:center; }\r\n\r\n		#message__100 img              { border-style:none; }\r\n		#message__100 a                { color:#d0a000; text-decoration:none; }\r\n		#message__100 a:hover          { text-decoration:underline; }\r\n	</style>\r\n'
WHERE  id=1 or id = 2 or id =3; 


UPDATE `tbl_settings_per_company` SET `d_email_css`='	<style type="text/css">\r\n		body,\r\n		#message__100                  { margin:0; padding:0; text-align:center; background-color:#e2e3c3; color:black;\r\n											font-family:Tahoma, Arial, sanf-serif; font-size:11px; }\r\n		#message__100 td               { vertical-align:top; font-size:11px; }\r\n		#message__100 th               { vertical-align:top; font-size:11px; }\r\n		#message__100 #layout_content { width:600px; min-width:600px; margin-left:auto; margin-right:auto; text-align:left; background-color:white; }\r\n		#message__100 #logo           { padding:15px; color:#0B71C3; background-color:white; font-size:17px; text-align:right; }\r\n		#message__100 #logo img       { float:left; }\r\n		#message__100 #openHours      { color:#0B71C3; font-size:12px; }\r\n		#message__100 #content        { padding:15px; margin-top:3em; background-color:white; clear:left; border-top: solid 2px #0B71C3; }\r\n		#message__100 #footer         { padding:5px; color:white; background-color:#0B71C3; text-align:center; }\r\n\r\n		#message__100 img              { border-style:none; }\r\n		#message__100 a                { color:#d0a000; text-decoration:none; }\r\n		#message__100 a:hover          { text-decoration:underline; }\r\n	</style>'
WHERE  id  =4 ;