-- 
-- Countries
-- 
CREATE TABLE [dbo].[Country] (
  [id] int IDENTITY(1, 1) NOT NULL,
  [Name] nvarchar(100) NULL,
  [Code2] varchar(2) NULL,
  [SortOrder] tinyint NULL,
  PRIMARY KEY CLUSTERED ([id])
)
GO
UPDATE Country SET SortOrder = 0
GO


INSERT INTO Country (Code2, Name, SortOrder) VALUES ('US', 'United States', 10); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CA', 'Canada', 9);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('UK', 'United Kingdom', 8);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MX', 'Mexico', 7);

INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AF', 'Afghanistan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AL', 'Albania', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('DZ', 'Algeria', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AS', 'American Samoa', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AD', 'Andorra', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AO', 'Angola', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AI', 'Anguilla', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AQ', 'Antarctica', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AG', 'Antigua and Barbuda', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AR', 'Argentina', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AM', 'Armenia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AW', 'Aruba', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AU', 'Australia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AT', 'Austria', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AZ', 'Azerbaijan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BS', 'Bahamas', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BH', 'Bahrain', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BD', 'Bangladesh', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BB', 'Barbados', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BY', 'Belarus', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BE', 'Belgium', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BZ', 'Belize', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BJ', 'Benin', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BM', 'Bermuda', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BT', 'Bhutan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BO', 'Bolivia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BA', 'Bosnia and Herzegovina', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BW', 'Botswana', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BV', 'Bouvet Island', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BR', 'Brazil', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('IO', 'British Indian Ocean Territory', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BN', 'Brunei Darussalam', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BG', 'Bulgaria', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BF', 'Burkina Faso', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('BI', 'Burundi', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KH', 'Cambodia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CM', 'Cameroon', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CV', 'Cape Verde', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KY', 'Cayman Islands', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CF', 'Central African Republic', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TD', 'Chad', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CL', 'Chile', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CN', 'China', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CX', 'Christmas Island', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CC', 'Cocos (Keeling) Islands', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CO', 'Colombia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CG', 'Congo', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CD', 'Congo, Democratic Republic', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CK', 'Cook Islands', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CR', 'Costa Rica', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('HR', 'Croatia (Hrvatska)', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CU', 'Cuba', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CY', 'Cyprus', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CZ', 'Czech Republic', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CS', 'Czechoslovakia (former)', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('DK', 'Denmark', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('DJ', 'Djibouti', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('DM', 'Dominica', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('DO', 'Dominican Republic', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TP', 'East Timor', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('EC', 'Ecuador', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('EG', 'Egypt', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SV', 'El Salvador', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GQ', 'Equatorial Guinea', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ER', 'Eritrea', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('EE', 'Estonia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ET', 'Ethiopia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MK', 'F.Y.R.O.M. (Macedonia)', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('FK', 'Falkland Islands (Malvinas)', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('FO', 'Faroe Islands', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('FJ', 'Fiji', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('FI', 'Finland', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('FR', 'France', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GF', 'French Guiana', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PF', 'French Polynesia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TF', 'French Southern Territories', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GA', 'Gabon', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GM', 'Gambia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GE', 'Georgia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('DE', 'Germany', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GH', 'Ghana', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GI', 'Gibraltar', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GB', 'Great Britain (UK)', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GR', 'Greece', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GL', 'Greenland', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GD', 'Grenada', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GP', 'Guadeloupe', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GU', 'Guam', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GT', 'Guatemala', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GN', 'Guinea', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GY', 'Guyana', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('HT', 'Haiti', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('HM', 'Heard and McDonald Islands', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('HN', 'Honduras', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('HK', 'Hong Kong', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('HU', 'Hungary', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('IS', 'Iceland', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('IN', 'India', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ID', 'Indonesia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('IR', 'Iran', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('IQ', 'Iraq', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('IE', 'Ireland', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('IL', 'Israel', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('IT', 'Italy', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('JM', 'Jamaica', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('JP', 'Japan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('JO', 'Jordan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KZ', 'Kazakhstan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KE', 'Kenya', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KI', 'Kiribati', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KP', 'Korea (North)', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KR', 'Korea (South)', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KW', 'Kuwait', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KG', 'Kyrgyzstan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LA', 'Laos', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LV', 'Latvia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LB', 'Lebanon', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LS', 'Lesotho', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LR', 'Liberia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LY', 'Libya', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LI', 'Liechtenstein', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LT', 'Lithuania', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LU', 'Luxembourg', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MO', 'Macau', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MG', 'Madagascar', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MW', 'Malawi', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MY', 'Malaysia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MV', 'Maldives', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ML', 'Mali', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MT', 'Malta', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MH', 'Marshall Islands', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MQ', 'Martinique', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MR', 'Mauritania', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MU', 'Mauritius', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('YT', 'Mayotte', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('FM', 'Micronesia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MD', 'Moldova', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MC', 'Monaco', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MN', 'Mongolia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MS', 'Montserrat', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MA', 'Morocco', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MZ', 'Mozambique', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MM', 'Myanmar', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NA', 'Namibia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NR', 'Nauru', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NP', 'Nepal', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NL', 'Netherlands', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AN', 'Netherlands Antilles', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NT', 'Neutral Zone', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NC', 'New Caledonia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NZ', 'New Zealand (Aotearoa)', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NI', 'Nicaragua', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NE', 'Niger', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NG', 'Nigeria', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NU', 'Niue', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NF', 'Norfolk Island', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('MP', 'Northern Mariana Islands', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('NO', 'Norway', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('OM', 'Oman', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PK', 'Pakistan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PW', 'Palau', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PA', 'Panama', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PG', 'Papua New Guinea', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PY', 'Paraguay', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PE', 'Peru', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PH', 'Philippines', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PN', 'Pitcairn', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PL', 'Poland', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PT', 'Portugal', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('PR', 'Puerto Rico', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('QA', 'Qatar', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('RE', 'Reunion', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('RO', 'Romania', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('RU', 'Russian Federation', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('RW', 'Rwanda', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('GS', 'S. Georgia and S. Sandwich Isls.', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('KN', 'Saint Kitts and Nevis', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LC', 'Saint Lucia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('VC', 'Saint Vincent &amp; the Grenadines', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('WS', 'Samoa', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SM', 'San Marino', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ST', 'Sao Tome and Principe', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SA', 'Saudi Arabia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SN', 'Senegal', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SC', 'Seychelles', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SL', 'Sierra Leone', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SG', 'Singapore', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SK', 'Slovak Republic', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SI', 'Slovenia', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SB', 'Solomon Islands', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SO', 'Somalia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ZA', 'South Africa', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ES', 'Spain', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('LK', 'Sri Lanka', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SD', 'Sudan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SR', 'Suriname', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SZ', 'Swaziland', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SE', 'Sweden', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('CH', 'Switzerland', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('SY', 'Syria', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TW', 'Taiwan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TJ', 'Tajikistan', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TZ', 'Tanzania', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TH', 'Thailand', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TG', 'Togo', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TK', 'Tokelau', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TO', 'Tonga', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TT', 'Trinidad and Tobago', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TN', 'Tunisia', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TR', 'Turkey', 0);
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TM', 'Turkmenistan', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TC', 'Turks and Caicos Islands', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('TV', 'Tuvalu', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('UG', 'Uganda', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('UA', 'Ukraine', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('AE', 'United Arab Emirates', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('UY', 'Uruguay', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('UZ', 'Uzbekistan', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('VU', 'Vanuatu', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('VA', 'Vatican City State (Holy See)', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('VE', 'Venezuela', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('VN', 'Viet Nam', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('VG', 'Virgin Islands (British)', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('WF', 'Wallis and Futuna Islands', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('EH', 'Western Sahara', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('YE', 'Yemen', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('YU', 'Yugoslavia', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ZR', 'Zaire', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ZM', 'Zambia', 0); 
INSERT INTO Country (Code2, Name, SortOrder) VALUES ('ZW', 'Zimbabwe', 0);
